version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - C:\Users\Usuário\Desktop\Dev\DbPostgree:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORTS}:5432